# Generated by Django 5.1.1 on 2025-09-18 10:37

import orders.fields
import orders.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_order_number_alter_order_delivery_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_phone',
            field=orders.fields.EncryptedPhoneField(max_length=320, validators=[orders.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_brand',
            field=orders.fields.EncryptedCharField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last_four',
            field=orders.fields.EncryptedCharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='orange_money_phone',
            field=orders.fields.EncryptedPhoneField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='orange_money_transaction_id',
            field=orders.fields.EncryptedCharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=orders.fields.EncryptedCharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_transaction_id',
            field=orders.fields.EncryptedCharField(blank=True, max_length=1600, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=orders.fields.EncryptedCharField(max_length=3200),
        ),
    ]
