# Generated by Django 5.1.1 on 2025-09-12 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_supplier_dropshipproduct_supplierinvoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité actuelle')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité réservée')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité disponible')),
                ('min_quantity', models.PositiveIntegerField(default=5, verbose_name='Quantité minimum')),
                ('max_quantity', models.PositiveIntegerField(default=1000, verbose_name='Quantité maximum')),
                ('reorder_quantity', models.PositiveIntegerField(default=10, verbose_name='Quantité de réapprovisionnement')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('low_stock', 'Stock faible'), ('out_of_stock', 'Rupture de stock'), ('discontinued', 'Discontinué')], default='out_of_stock', max_length=20, verbose_name='Statut du stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Stock actif')),
                ('auto_reorder', models.BooleanField(default=False, verbose_name='Réapprovisionnement automatique')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_movement', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('return', 'Retour')], max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('reason', models.CharField(max_length=200, verbose_name='Raison du mouvement')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='Quantité avant')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Quantité après')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.stock', verbose_name='Stock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
