# Generated by Django 5.1.1 on 2025-09-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_barcode_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Code SKU'),
        ),
    ]
