# Generated by Django 5.1.1 on 2025-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipproduct',
            name='stock_virtuel',
            field=models.PositiveIntegerField(default=0, help_text='Stock virtuel (disponible chez le fournisseur)', verbose_name='Stock virtuel (quantité disponible chez le fournisseur)'),
        ),
    ]
