# Generated by Django 5.1.1 on 2025-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_dropshipproduct_stock_virtuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshipproduct',
            name='stock_virtuel',
        ),
        migrations.AlterField(
            model_name='dropshipproduct',
            name='virtual_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock virtuel (disponible chez le fournisseur)', verbose_name='Stock virtuel (quantité disponible chez le fournisseur)'),
        ),
    ]
