# Generated by Django 5.1.1 on 2025-09-17 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Entreprise', max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_description', models.TextField(blank=True, help_text='Description courte de votre entreprise', verbose_name="Description de l'entreprise")),
                ('logo', models.ImageField(blank=True, help_text='Format recommandé: PNG ou SVG, taille optimale: 200x80px', null=True, upload_to='company/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])], verbose_name="Logo de l'entreprise")),
                ('address', models.TextField(blank=True, help_text="Adresse complète de l'entreprise", verbose_name='Adresse complète')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('tax_number', models.CharField(blank=True, help_text='Numéro de TVA ou Registre de Commerce', max_length=50, verbose_name='Numéro de TVA/RC')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement")),
                ('show_logo_on_invoices', models.BooleanField(default=True, verbose_name='Afficher le logo sur les factures')),
                ('show_logo_on_receipts', models.BooleanField(default=True, verbose_name='Afficher le logo sur les reçus')),
                ('show_logo_on_reports', models.BooleanField(default=True, verbose_name='Afficher le logo sur les rapports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
    ]
